# fly.toml app configuration file generated for still-sun-3981 on 2023-10-12T21:59:52+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "still-sun-3981"
primary_region = "ams"
console_command = "/rails/bin/rails console"

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[statics]]
  guest_path = "/rails/client/public"
  url_prefix = "/"
